### ISSUE TITLE
"Could not acquire lock for ClassLoader cache creation." with TYPO3 6.2

### ISSUE THREAD

**Issue by mbrodala** [Nimut/TYPO3-testing-framework#18]
While trying to run some unit tests I get the following error:

```
PHPUnit 5.7.15 by Sebastian Bergmann and contributors.

EPHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Could not acquire lock for ClassLoader cache creation.' in /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php:761
Stack trace:
#0 /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php(247): TYPO3\CMS\Core\Core\ClassLoader->acquireLock()
#1 /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php(182): TYPO3\CMS\Core\Core\ClassLoader->buildCachedClassLoadingInformation('php_invoker', 'PHP_Invoker')
#2 [internal function]: TYPO3\CMS\Core\Core\ClassLoader->loadClass('PHP_Invoker')
#3 [internal function]: spl_autoload_call('PHP_Invoker')
#4 /.../vendor/phpunit/phpunit/src/Util/Blacklist.php(91): class_exists('PHP_Invoker')
#5 /.../vendor/phpunit/phpunit/src/Util/Blacklist.php(7 in /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php on line 761

Fatal error: Uncaught exception 'RuntimeException' with message 'Could not acquire lock for ClassLoader cache creation.' in /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php on line 761

RuntimeException: Could not acquire lock for ClassLoader cache creation. in /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php on line 761

Call Stack:
    0.0001     253672   1. {main}() /.../vendor/phpunit/phpunit/phpunit:0
    0.0069    1338896   2. PHPUnit_TextUI_Command::main() /.../vendor/phpunit/phpunit/phpunit:52
    0.0069    1339672   3. PHPUnit_TextUI_Command->run() /.../vendor/phpunit/phpunit/src/TextUI/Command.php:118
    0.1401   11372544   4. PHPUnit_TextUI_TestRunner->doRun() /.../vendor/phpunit/phpunit/src/TextUI/Command.php:188
    0.1466   12014136   5. PHPUnit_Framework_TestSuite->run() /.../vendor/phpunit/phpunit/src/TextUI/TestRunner.php:521
    0.1474   12034184   6. PHPUnit_Framework_TestSuite->run() /.../vendor/phpunit/phpunit/src/Framework/TestSuite.php:728
    0.1510   12039528   7. PHPUnit_Framework_TestCase->run() /.../vendor/phpunit/phpunit/src/Framework/TestSuite.php:728
    0.1510   12041664   8. PHPUnit_Framework_TestResult->run() /.../vendor/phpunit/phpunit/src/Framework/TestCase.php:926
   30.4843   18764784   9. PHPUnit_Framework_TestResult->addError() /.../vendor/phpunit/phpunit/src/Framework/TestResult.php:872
   30.4847   18791360  10. PHPUnit_Util_Log_JUnit->addError() /.../vendor/phpunit/phpunit/src/Framework/TestResult.php:264
   30.4847   18791640  11. PHPUnit_Util_Log_JUnit->doAddFault() /.../vendor/phpunit/phpunit/src/Util/Log/JUnit.php:125
   30.4849   18813176  12. PHPUnit_Util_Filter::getFilteredStacktrace() /.../vendor/phpunit/phpunit/src/Util/Log/JUnit.php:451
   30.4852   18833440  13. PHPUnit_Util_Blacklist->isBlacklisted() /.../vendor/phpunit/phpunit/src/Util/Filter.php:69
   30.4852   18833584  14. PHPUnit_Util_Blacklist->initialize() /.../vendor/phpunit/phpunit/src/Util/Blacklist.php:74
   30.4852   18834496  15. class_exists() /.../vendor/phpunit/phpunit/src/Util/Blacklist.php:91
   30.4852   18834776  16. spl_autoload_call() /.../vendor/phpunit/phpunit/src/Util/Blacklist.php:91
   30.4853   18835432  17. TYPO3\CMS\Core\Core\ClassLoader->loadClass() /.../vendor/phpunit/phpunit/src/Util/Blacklist.php:91
   30.4853   18835560  18. TYPO3\CMS\Core\Core\ClassLoader->buildCachedClassLoadingInformation() /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php:182
   30.4853   18835608  19. TYPO3\CMS\Core\Core\ClassLoader->acquireLock() /.../vendor/typo3/cms/typo3/sysext/core/Classes/Core/ClassLoader.php:247
```

There is a lock file in `$TYPO3_PATH_WEB/typo3temp/locks` after this.

**Comment by IchHabRecht** [comment]
Hi Mathias,
Is this error popping up every time running the tests? I have this one from time to time on my dev system and it seems to be related to multiple incoming requests at the same time.

**Comment by helhum** [comment]
Do you run unit tests in parallel, too?

**Comment by mbrodala** [comment]
I'd also suspect tests running in parallel, I'll check and report back.

**Comment by mbrodala** [comment]
I've updated the output with a stack trace.

**Comment by mbrodala** [comment]
There must really be a process or similar causing a deadlock. If I manually drop the file in `typo3temp/locks` while a test run hangs, the test immediately finishes as expected.

**Comment by mbrodala** [comment]
Everything seems to work fine if I modify `ClassLoader::getLocker()` to use `Locker::LOCKING_METHOD_FLOCK`.

**Comment by mbrodala** [comment]
OK, I got closer. In the specific test which caused this issue I used a fake class name `TestClass` simply for argument matching. This class obviously cannot be loaded by Composer and as soon as the TYPO3 class loader tries to, it deadlocks.

Thus the simplest testcase to reproduce this:

```php
/**
 * @test
 */
public function causesTypo3ClassLoaderDeadLock()
{
    $mock = $this->createMock('TestClass');
}
```

Interestingly the lock file in `typo3temp/locks` isn't removed even after a successful execution ...

**Comment by mbrodala** [comment]
This is as far as I'll go for now, I don't have that much time to spent investigating this issue further since the old class loader of TYPO3 is complex and especially the locking is hard to debug.

As mentioned I've fixed the issue for me by switching to an existing class name.

**Comment by mbrodala** [comment]
I see the same issue in another package where I `prophesize()` an existing class. :-/

**Comment by IchHabRecht** [comment]
Hi Mathias,

Do you have some more information on this now or can we close this issue?

**Comment by mbrodala** [comment]
So far I haven't had the time to look further into this. It's not resolved but I guess I will become irrelevant over time now that 6.2 is technically dead. I'll leave a comment if I find out something new.

**Comment by mbrodala** [comment]
As a consequence a workaround is to ensure that the TYPO3 6.2 class loader is never invoked. Thus never use, mock or check for non-existing classes. Everything must be loadable by Composer.
